language: node_js

node_js:
  - "8.9"
  - "node"

cache:
  directories:
    - node_modules

before_install:
  - git clone https://github.com/facebook/watchman.git
  - cd watchman
  - git checkout v4.9.0
  - ./autogen.sh
  - ./configure 
  - make
  - sudo make install
